// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_wehrmacht");
	self attach("xmodel/head_german_normandy_josh", "", true);
	self.awe_headmodel = "xmodel/head_german_normandy_josh";
	self setViewmodel("xmodel/viewmodel_hands_german");
}

precache()
{
	precacheModel("xmodel/playerbody_german_wehrmacht");
	precacheModel("xmodel/head_german_normandy_josh");
	precacheModel("xmodel/viewmodel_hands_german");
}
